LogTime yes
LogClean no
LogSyslog no

TCPSocket 3310
LocalSocket /tmp/clamd.sock

DatabaseDirectory /var/lib/clamav

ScanArchive yes
MaxScanSize 419430400
MaxFileSize 104857600
MaxRecursion 16
MaxFiles 10000
StreamMaxLength 104857600

MaxThreads 10
